import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { AuthGuard } from './shared/guard/auth.guard';
import { HomeComponent } from './home/home.component';
import { CommonModule } from '@angular/common';
import { BrowserModule } from '@angular/platform-browser';
import { DetailProductComponent } from './detail-product/detail-product.component';
import { ShoppingCartComponent } from './shopping-cart/shopping-cart.component';
const routes: Routes = [
  {
    path: '',
    loadChildren: () => import('./login/login.module').then((m) => m.LoginModule),
  },
  {
    path: 'home',
    component: HomeComponent, canActivate: [AuthGuard]// We validate route through authenticated login
  },
  {
    //in this route we will see the details of the product 
    //by means of the id generated by the document from firebase
    path: 'detailProduct/:id',
    component: DetailProductComponent
  },
  {
    //route to see the shopping cart whether or not there are products in the
    path: 'shoppingCard',
    component: ShoppingCartComponent
  },
  {
    path:'**', redirectTo: 'home'
  }
];

@NgModule({
  imports: [RouterModule.forRoot(routes),CommonModule,BrowserModule],
  exports: [RouterModule]
})
export class AppRoutingModule { }
